CREATE DATABASE QLKS

USE QLKS

CREATE TABLE QUANLI
(
	MAQL CHAR(5) PRIMARY KEY,
	TENQUANLI NVARCHAR(50),
	USERNAME VARCHAR(20),
	PASS VARCHAR(20),
	CCCD CHAR(12),
	SDT CHAR(10),
	NGAYSINH DATETIME,
	GIOITINH VARCHAR(3),
	AVATAR  VARBINARY(MAX)
)

CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY,
	TENKH NVARCHAR(50),
	USERNAME VARCHAR(20),
	PASS VARCHAR(20),
	CCCD CHAR(12),
	SDT CHAR(10),
	NGAYSINH DATETIME,
	GIOITINH VARCHAR(3),
	AVATAR  VARBINARY(MAX)
)

	
CREATE TABLE PHONG
(
	MAPHONG CHAR(5) PRIMARY KEY,
	TENPHONG VARCHAR(20),
	LOAIPHONG SMALLINT, --VIP, THUONG...
	SOGIUONG SMALLINT, --4,6,8...
	TRANGTHAI VARCHAR(10),
)

CREATE TABLE THUEPHONG
(
	MATHUEPHONG CHAR(5) PRIMARY KEY,
	MAKH CHAR(5) NULL,
	MAPHONG CHAR(5),
	NGAYBD DATE,
	NGAYKT DATE,
)
ALTER TABLE THUEPHONG 
ADD CONSTRAINT FK_THUEPHONG_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE THUEPHONG 
ADD CONSTRAINT FK_THUEPHONG_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)


CREATE TABLE DICHVU (
	MADV CHAR(5) PRIMARY KEY,
	TENDV NVARCHAR(100),
	DONGIA MONEY,
	SOLUONG SMALLINT --SỐ LƯỢNG DỊCH VỤ ĐÓ CÒN LẠI
);

CREATE TABLE CHITIETDV 
(
	MATHUEPHONG CHAR(5),
    MADV CHAR(5), 
    SOLUONG INT, -- SỐ LƯỢNG PHÒNG ĐÓ ĐẶT
    THANHTIEN MONEY,
    PRIMARY KEY (MATHUEPHONG, MADV),
);
ALTER TABLE CHITIETDV
ADD CONSTRAINT FK_CTDICHVU_THUEPHONG FOREIGN KEY (MATHUEPHONG) REFERENCES THUEPHONG(MATHUEPHONG)

ALTER TABLE CHITIETDV
ADD CONSTRAINT FK_CTDICHVU_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)

CREATE TABLE NHANVIEN
(
	MANV CHAR(5) PRIMARY KEY,
	TENNV VARCHAR(50),
	CCCD CHAR(12),
	SDT CHAR(10),
	NGAYSINH DATETIME,
	GIOITINH VARCHAR(3),
	BOPHAN VARCHAR(20), --LỄ TÂN, PHỤC VỤ PHÒNG, ẨM THỰC,...
)

CREATE TABLE HOADON (
	SOHD INT PRIMARY KEY,
	NGAYLAP DATETIME,
	TONGTIEN MONEY,
);

CREATE TABLE CTHD (
	SOHD INT,
	MAPHONG CHAR(5),
	MANV CHAR(5),
	THANHTIEN MONEY,
	PRIMARY KEY(SOHD, MAPHONG),
  
);
ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD)
    
ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
    
ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_THUEPHONG FOREIGN KEY (MAPHONG) REFERENCES THUEPHONG(MATHUEPHONG)  
